import type { Language, LetterDefinition } from './types.js';

export const letterDistributions: Record<Language, LetterDefinition[]> = {
  English: [
    { score: 0, count: 2 },
    { letter: 'E', score: 1, count: 12 },
    { letter: 'A', score: 1, count: 9 },
    { letter: 'I', score: 1, count: 9 },
    { letter: 'O', score: 1, count: 8 },
    { letter: 'N', score: 1, count: 6 },
    { letter: 'R', score: 1, count: 6 },
    { letter: 'T', score: 1, count: 6 },
    { letter: 'L', score: 1, count: 4 },
    { letter: 'S', score: 1, count: 4 },
    { letter: 'U', score: 1, count: 4 },
    { letter: 'D', score: 2, count: 4 },
    { letter: 'G', score: 2, count: 3 },
    { letter: 'B', score: 3, count: 2 },
    { letter: 'C', score: 3, count: 2 },
    { letter: 'M', score: 3, count: 2 },
    { letter: 'P', score: 3, count: 2 },
    { letter: 'F', score: 4, count: 2 },
    { letter: 'H', score: 4, count: 2 },
    { letter: 'V', score: 4, count: 2 },
    { letter: 'W', score: 4, count: 2 },
    { letter: 'Y', score: 4, count: 2 },
    { letter: 'K', score: 5, count: 1 },
    { letter: 'J', score: 8, count: 1 },
    { letter: 'X', score: 8, count: 1 },
    { letter: 'Q', score: 10, count: 1 },
    { letter: 'Z', score: 10, count: 1 },
  ],
  Estonian: [
    { score: 0, count: 2 },
    { letter: 'E', score: 1, count: 9 },
    { letter: 'A', score: 1, count: 10 },
    { letter: 'I', score: 1, count: 9 },
    { letter: 'O', score: 1, count: 5 },
    { letter: 'N', score: 2, count: 4 },
    { letter: 'R', score: 2, count: 2 },
    { letter: 'T', score: 1, count: 7 },
    { letter: 'L', score: 1, count: 5 },
    { letter: 'S', score: 1, count: 8 },
    { letter: 'U', score: 1, count: 5 },
    { letter: 'D', score: 2, count: 4 },
    { letter: 'G', score: 3, count: 2 },
    { letter: 'B', score: 4, count: 1 },
    { letter: 'M', score: 2, count: 4 },
    { letter: 'P', score: 4, count: 2 },
    { letter: 'F', score: 4, count: 1 },
    { letter: 'H', score: 4, count: 2 },
    { letter: 'V', score: 3, count: 2 },
    { letter: 'K', score: 1, count: 5 },
    { letter: 'J', score: 4, count: 2 },
    { letter: 'Z', score: 10, count: 1 },
    { letter: '\u0160', score: 10, count: 1 },
    { letter: '\u017D', score: 10, count: 1 },
    { letter: '\u00D5', score: 5, count: 2 },
    { letter: '\u00C4', score: 5, count: 2 },
    { letter: '\u00D6', score: 6, count: 2 },
    { letter: '\u00DC', score: 5, count: 2 },
  ],
  Czech: [
    { score: 0, count: 2 },
    { letter: 'A', score: 1, count: 5 },
    { letter: '\u00C1', score: 2, count: 2 },
    { letter: 'B', score: 3, count: 2 },
    { letter: 'C', score: 2, count: 3 },
    { letter: '\u010C', score: 4, count: 1 },
    { letter: 'D', score: 1, count: 3 },
    { letter: '\u010E', score: 8, count: 1 },
    { letter: 'E', score: 1, count: 5 },
    { letter: '\u00C9', score: 3, count: 2 },
    { letter: '\u011A', score: 3, count: 2 },
    { letter: 'F', score: 5, count: 1 },
    { letter: 'G', score: 5, count: 1 },
    { letter: 'H', score: 2, count: 3 },
    { letter: 'I', score: 1, count: 4 },
    { letter: '\u00CD', score: 2, count: 3 },
    { letter: 'J', score: 2, count: 2 },
    { letter: 'K', score: 1, count: 3 },
    { letter: 'L', score: 1, count: 3 },
    { letter: 'M', score: 2, count: 3 },
    { letter: 'N', score: 1, count: 5 },
    { letter: '\u0147', score: 6, count: 1 },
    { letter: 'O', score: 1, count: 6 },
    { letter: '\u00D3', score: 7, count: 1 },
    { letter: 'P', score: 1, count: 3 },
    { letter: 'R', score: 1, count: 3 },
    { letter: '\u0158', score: 4, count: 2 },
    { letter: 'S', score: 1, count: 4 },
    { letter: '\u0160', score: 4, count: 2 },
    { letter: 'T', score: 1, count: 4 },
    { letter: '\u0164', score: 7, count: 1 },
    { letter: 'U', score: 2, count: 3 },
    { letter: '\u00DA', score: 5, count: 1 },
    { letter: '\u016E', score: 4, count: 1 },
    { letter: 'V', score: 1, count: 4 },
    { letter: 'X', score: 10, count: 1 },
    { letter: 'Y', score: 2, count: 2 },
    { letter: '\u00DD', score: 4, count: 2 },
    { letter: 'Z', score: 2, count: 2 },
    { letter: '\u017D', score: 4, count: 1 },
  ],
  French: [
    { score: 0, count: 2 },
    { letter: 'E', score: 1, count: 15 },
    { letter: 'A', score: 1, count: 9 },
    { letter: 'I', score: 1, count: 8 },
    { letter: 'N', score: 1, count: 6 },
    { letter: 'O', score: 1, count: 6 },
    { letter: 'R', score: 1, count: 6 },
    { letter: 'S', score: 1, count: 6 },
    { letter: 'T', score: 1, count: 6 },
    { letter: 'U', score: 1, count: 6 },
    { letter: 'L', score: 1, count: 5 },
    { letter: 'D', score: 2, count: 3 },
    { letter: 'G', score: 2, count: 2 },
    { letter: 'M', score: 3, count: 3 },
    { letter: 'B', score: 3, count: 2 },
    { letter: 'C', score: 3, count: 2 },
    { letter: 'P', score: 3, count: 2 },
    { letter: 'F', score: 4, count: 2 },
    { letter: 'H', score: 4, count: 2 },
    { letter: 'V', score: 4, count: 2 },
    { letter: 'J', score: 8, count: 1 },
    { letter: 'Q', score: 8, count: 1 },
    { letter: 'K', score: 10, count: 1 },
    { letter: 'W', score: 10, count: 1 },
    { letter: 'X', score: 10, count: 1 },
    { letter: 'Y', score: 10, count: 1 },
    { letter: 'Z', score: 10, count: 1 },
  ],
  German: [
    { score: 0, count: 2 },
    { letter: 'E', score: 1, count: 15 },
    { letter: 'N', score: 1, count: 9 },
    { letter: 'S', score: 1, count: 7 },
    { letter: 'I', score: 1, count: 6 },
    { letter: 'R', score: 1, count: 6 },
    { letter: 'T', score: 1, count: 6 },
    { letter: 'U', score: 1, count: 6 },
    { letter: 'A', score: 1, count: 5 },
    { letter: 'D', score: 1, count: 4 },
    { letter: 'H', score: 2, count: 4 },
    { letter: 'G', score: 2, count: 3 },
    { letter: 'L', score: 2, count: 3 },
    { letter: 'O', score: 2, count: 3 },
    { letter: 'M', score: 3, count: 4 },
    { letter: 'B', score: 3, count: 2 },
    { letter: 'W', score: 3, count: 1 },
    { letter: 'Z', score: 3, count: 1 },
    { letter: 'C', score: 4, count: 2 },
    { letter: 'F', score: 4, count: 2 },
    { letter: 'K', score: 4, count: 2 },
    { letter: 'P', score: 4, count: 1 },
    { letter: '\u00C4', score: 6, count: 1 },
    { letter: 'J', score: 6, count: 1 },
    { letter: '\u00DC', score: 6, count: 1 },
    { letter: 'V', score: 6, count: 1 },
    { letter: '\u00D6', score: 8, count: 1 },
    { letter: 'X', score: 8, count: 1 },
    { letter: 'Q', score: 10, count: 1 },
    { letter: 'Y', score: 10, count: 1 },
  ],
  Hungarian: [
    { score: 0, count: 2 },
    { letter: 'A', score: 1, count: 6 },
    { letter: 'E', score: 1, count: 6 },
    { letter: 'K', score: 1, count: 6 },
    { letter: 'T', score: 1, count: 5 },
    { letter: '\u00C1', score: 1, count: 4 },
    { letter: 'L', score: 1, count: 4 },
    { letter: 'N', score: 1, count: 4 },
    { letter: 'R', score: 1, count: 4 },
    { letter: 'I', score: 1, count: 3 },
    { letter: 'M', score: 1, count: 3 },
    { letter: 'O', score: 1, count: 3 },
    { letter: 'S', score: 1, count: 3 },
    { letter: 'B', score: 2, count: 3 },
    { letter: 'D', score: 2, count: 3 },
    { letter: 'G', score: 2, count: 3 },
    { letter: '\u00D3', score: 2, count: 3 },
    { letter: '\u00C9', score: 3, count: 3 },
    { letter: 'H', score: 3, count: 2 },
    { letter: 'SZ', score: 3, count: 2 },
    { letter: 'V', score: 3, count: 2 },
    { letter: 'F', score: 4, count: 2 },
    { letter: 'GY', score: 4, count: 2 },
    { letter: 'J', score: 4, count: 2 },
    { letter: '\u00D6', score: 4, count: 2 },
    { letter: 'P', score: 4, count: 2 },
    { letter: 'U', score: 4, count: 2 },
    { letter: '\u00DC', score: 4, count: 2 },
    { letter: 'Z', score: 4, count: 2 },
    { letter: 'C', score: 5, count: 1 },
    { letter: '\u00CD', score: 5, count: 1 },
    { letter: 'NY', score: 5, count: 1 },
    { letter: 'CS', score: 7, count: 1 },
    { letter: '\u0150', score: 7, count: 1 },
    { letter: '\u0150', score: 7, count: 1 },
    { letter: '\u00DA', score: 7, count: 1 },
    { letter: '\u0170', score: 7, count: 1 },
    { letter: 'LY', score: 8, count: 1 },
    { letter: 'ZS', score: 8, count: 1 },
    { letter: 'TY', score: 10, count: 1 },
  ],
  Nederlands: [
    { score: 0, count: 2 },
    { letter: 'A', score: 1, count: 6 },
    { letter: 'B', score: 3, count: 2 },
    { letter: 'C', score: 5, count: 2 },
    { letter: 'D', score: 2, count: 5 },
    { letter: 'E', score: 1, count: 18 },
    { letter: 'F', score: 4, count: 2 },
    { letter: 'G', score: 3, count: 3 },
    { letter: 'H', score: 4, count: 2 },
    { letter: 'I', score: 1, count: 4 },
    { letter: 'J', score: 4, count: 2 },
    { letter: 'K', score: 3, count: 3 },
    { letter: 'L', score: 3, count: 3 },
    { letter: 'M', score: 3, count: 3 },
    { letter: 'N', score: 1, count: 10 },
    { letter: 'O', score: 1, count: 6 },
    { letter: 'P', score: 3, count: 2 },
    { letter: 'Q', score: 10, count: 1 },
    { letter: 'R', score: 2, count: 5 },
    { letter: 'S', score: 2, count: 5 },
    { letter: 'T', score: 2, count: 5 },
    { letter: 'U', score: 4, count: 3 },
    { letter: 'V', score: 4, count: 2 },
    { letter: 'W', score: 5, count: 2 },
    { letter: 'X', score: 8, count: 1 },
    { letter: 'Y', score: 4, count: 2 },
    { letter: 'Z', score: 4, count: 2 },
  ],
  Portuguese: [
    { score: 0, count: 3 },
    { letter: 'A', score: 1, count: 14 },
    { letter: 'E', score: 1, count: 11 },
    { letter: 'I', score: 1, count: 10 },
    { letter: 'O', score: 1, count: 10 },
    { letter: 'S', score: 1, count: 8 },
    { letter: 'U', score: 1, count: 7 },
    { letter: 'M', score: 1, count: 6 },
    { letter: 'R', score: 1, count: 6 },
    { letter: 'T', score: 1, count: 5 },
    { letter: 'D', score: 2, count: 5 },
    { letter: 'L', score: 2, count: 5 },
    { letter: 'C', score: 2, count: 4 },
    { letter: 'P', score: 2, count: 4 },
    { letter: 'N', score: 3, count: 4 },
    { letter: 'B', score: 3, count: 3 },
    { letter: '\u00C7', score: 3, count: 2 },
    { letter: 'F', score: 4, count: 2 },
    { letter: 'G', score: 4, count: 2 },
    { letter: 'H', score: 4, count: 2 },
    { letter: 'V', score: 4, count: 2 },
    { letter: 'J', score: 5, count: 2 },
    { letter: 'Q', score: 6, count: 1 },
    { letter: 'X', score: 8, count: 1 },
    { letter: 'Z', score: 8, count: 1 },
  ],
  Slovenian: [
    { letter: 'A', score: 1, count: 10 },
    { letter: 'B', score: 4, count: 2 },
    { letter: 'C', score: 8, count: 1 },
    { letter: '\u010C', score: 5, count: 1 },
    { letter: 'D', score: 2, count: 4 },
    { letter: 'E', score: 1, count: 11 },
    { letter: 'F', score: 10, count: 1 },
    { letter: 'G', score: 4, count: 2 },
    { letter: 'H', score: 5, count: 1 },
    { letter: 'I', score: 1, count: 9 },
    { letter: 'J', score: 1, count: 4 },
    { letter: 'K', score: 3, count: 3 },
    { letter: 'L', score: 1, count: 4 },
    { letter: 'M', score: 3, count: 2 },
    { letter: 'N', score: 1, count: 7 },
    { letter: 'O', score: 1, count: 8 },
    { letter: 'P', score: 3, count: 2 },
    { letter: 'R', score: 1, count: 6 },
    { letter: 'S', score: 1, count: 6 },
    { letter: '\u0160', score: 6, count: 1 },
    { letter: 'T', score: 1, count: 4 },
    { letter: 'U', score: 3, count: 2 },
    { letter: 'V', score: 2, count: 4 },
    { letter: 'Z', score: 4, count: 2 },
    { letter: '\u017D', score: 10, count: 1 },
  ],
  Test: [
    { score: 0, count: 1 },
    { letter: 'E', score: 1, count: 1 },
    { letter: 'N', score: 1, count: 1 },
    { letter: 'S', score: 1, count: 1 },
    { letter: 'I', score: 1, count: 1 },
    { letter: 'R', score: 1, count: 1 },
    { letter: 'T', score: 1, count: 1 },
    { letter: 'U', score: 1, count: 1 },
    { letter: 'A', score: 1, count: 1 },
    { letter: 'D', score: 1, count: 1 },
    { letter: 'H', score: 2, count: 1 },
    { letter: 'G', score: 2, count: 1 },
    { letter: 'L', score: 2, count: 1 },
    { letter: 'O', score: 2, count: 1 },
    { letter: 'M', score: 3, count: 1 },
    { letter: 'B', score: 3, count: 1 },
    { letter: 'W', score: 3, count: 1 },
    { letter: 'Z', score: 3, count: 1 },
    { letter: 'C', score: 4, count: 1 },
    { letter: 'F', score: 4, count: 1 },
    { letter: 'K', score: 4, count: 1 },
  ],
};
